-- Fix activity_type column to be ENUM type
ALTER TABLE activity_entries MODIFY COLUMN activity_type ENUM(
    'RUNNING', 'WALKING', 'CYCLING', 'SWIMMING', 'WEIGHT_TRAINING', 
    'YOGA', 'PILATES', 'DANCING', 'HIKING', 'TENNIS', 'BASKETBALL', 
    'SOCCER', 'GOLF', 'SKIING', 'ROWING', 'ELLIPTICAL', 'STAIR_CLIMBER'
) NOT NULL; 